/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import connector.ServerConnector;
import controller.ChatController;
import java.net.Inet4Address;
import java.net.MalformedURLException;
import java.net.UnknownHostException;
import java.rmi.NotBoundException;
import java.rmi.RemoteException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.text.DefaultCaret;
import static javax.swing.text.DefaultCaret.ALWAYS_UPDATE;
import observer.ChatBox;

/**
 *
 * @author Imalka Gunawardana
 */
public class ChatBoxView extends javax.swing.JFrame {

    private ChatController chatController;
    private ChatBox chatBox;
    private String user;

    /**
     * Creates new form FirstChatBox
     */
    public ChatBoxView(ChatBox chatBox, String user) {
        initComponents();
        setSize(1025, 770);
        setLocation(0, 0);
        setVisible(true);
        setChatServer(chatBox, user);
        updateMessage();
        txtEnterMessage.requestFocus();
    }

    private void setChatServer(ChatBox chatBox, String user) {
        try {
            chatController = ServerConnector.getConnector().getChatController();
            lblHead.setText(Inet4Address.getLocalHost().getHostName() + " - (" + Inet4Address.getLocalHost().getHostAddress() + ")");
            this.chatBox = chatBox;
            this.user = user;
            lblUser.setText("User : " + user);
        } catch (NotBoundException ex) {
            Logger.getLogger(ChatBoxView.class.getName()).log(Level.SEVERE, null, ex);
        } catch (MalformedURLException ex) {
            Logger.getLogger(ChatBoxView.class.getName()).log(Level.SEVERE, null, ex);
        } catch (RemoteException ex) {
            Logger.getLogger(ChatBoxView.class.getName()).log(Level.SEVERE, null, ex);
        } catch (UnknownHostException ex) {
            Logger.getLogger(ChatBoxView.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    public void updateMessage() {
        try {
            String text = "";
            String[] textLines = chatController.getMessage().split("\n");
            for (int i = 0; i < textLines.length; i++) {
                if (textLines[i].matches("[\\w\\W]+" + user + "[ /][\\w\\W]+")) {
                    textLines[i] = textLines[i].replaceAll("Received from :- " + user, "Sent from :- " + user);
                }
            }
            for (String textLine : textLines) {
                text += textLine + "\n";
            }
            txtMessages.setText(text);
            DefaultCaret caret = (DefaultCaret) txtMessages.getCaret();
            caret.setUpdatePolicy(ALWAYS_UPDATE);
        } catch (RemoteException ex) {
            Logger.getLogger(ChatBoxView.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    public void updateList() {
        try {
            ArrayList<String> allDevices = chatController.getAllDevices();
            String list = "";
            for (String allDevice : allDevices) {
                if (!user.equals(allDevice)) {
                    list += allDevice + "\n";
                }
            }
            txtClients.setText(list);
        } catch (RemoteException ex) {
            Logger.getLogger(ChatBoxView.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txtEnterMessage = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtMessages = new javax.swing.JTextArea();
        btnSend = new javax.swing.JButton();
        lblHead1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lblHead = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtClients = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        lblUser = new javax.swing.JLabel();
        btnLogout = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(null);

        txtEnterMessage.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtEnterMessage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEnterMessageActionPerformed(evt);
            }
        });
        jPanel1.add(txtEnterMessage);
        txtEnterMessage.setBounds(9, 620, 990, 43);

        txtMessages.setColumns(20);
        txtMessages.setFont(new java.awt.Font("Monospaced", 0, 16)); // NOI18N
        txtMessages.setRows(5);
        jScrollPane1.setViewportView(txtMessages);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(340, 100, 660, 490);

        btnSend.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnSend.setText("Send");
        btnSend.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSendActionPerformed(evt);
            }
        });
        jPanel1.add(btnSend);
        btnSend.setBounds(400, 680, 220, 31);

        lblHead1.setBackground(new java.awt.Color(255, 255, 204));
        lblHead1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        lblHead1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblHead1.setText("Chat Box");
        lblHead1.setOpaque(true);
        jPanel1.add(lblHead1);
        lblHead1.setBounds(0, -6, 1010, 60);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel2.setText("Enter Message Here");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(10, 600, 182, 16);

        lblHead.setBackground(new java.awt.Color(255, 255, 204));
        lblHead.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblHead.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblHead.setOpaque(true);
        jPanel1.add(lblHead);
        lblHead.setBounds(0, 50, 1010, 20);

        txtClients.setColumns(20);
        txtClients.setFont(new java.awt.Font("Monospaced", 1, 16)); // NOI18N
        txtClients.setRows(5);
        jScrollPane2.setViewportView(txtClients);

        jPanel1.add(jScrollPane2);
        jScrollPane2.setBounds(10, 130, 320, 460);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Available Clients (Online)");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(10, 106, 320, 20);

        lblUser.setBackground(new java.awt.Color(255, 255, 204));
        lblUser.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblUser.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblUser.setOpaque(true);
        jPanel1.add(lblUser);
        lblUser.setBounds(0, 70, 1010, 20);

        btnLogout.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        btnLogout.setText("Logout");
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });
        jPanel1.add(btnLogout);
        btnLogout.setBounds(910, 680, 79, 25);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 1010, 730);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSendActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSendActionPerformed
        sendData();
    }//GEN-LAST:event_btnSendActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        try {
            chatBox.remove(user);
        } catch (RemoteException ex) {
            Logger.getLogger(ChatBoxView.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_formWindowClosing

    private void txtEnterMessageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEnterMessageActionPerformed
        sendData();
    }//GEN-LAST:event_txtEnterMessageActionPerformed

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        try {
            chatBox.remove(user);
            new LoginForm();
            this.dispose();
        } catch (RemoteException ex) {
            Logger.getLogger(ChatBoxView.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnLogoutActionPerformed

    private void sendData() {
        try {
            chatController.setMessage(txtEnterMessage.getText() + " - (Received from :- " + user);
        } catch (RemoteException ex) {
            Logger.getLogger(ChatBoxView.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ChatBoxView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ChatBoxView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ChatBoxView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ChatBoxView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new ChatBoxView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton btnSend;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblHead;
    private javax.swing.JLabel lblHead1;
    private javax.swing.JLabel lblUser;
    private javax.swing.JTextArea txtClients;
    private javax.swing.JTextField txtEnterMessage;
    private javax.swing.JTextArea txtMessages;
    // End of variables declaration//GEN-END:variables

}
